package com.ovelayos.animeav1;

import org.json.JSONObject;

final class SiteIntegration {
    private SiteIntegration() {}

    static String install(String downloadLabel) {
        return "(function(){" +
                "window.__animeav1AndroidLabel=" + JSONObject.quote(downloadLabel) + ";" +
                "window.__animeav1AndroidVersion=" + JSONObject.quote("AnimeAV1 Android v" + BuildConfig.VERSION_NAME) + ";" +
                "function n(s){return (s||'').replace(/\\s+/g,' ').trim().toLowerCase();}" +
                "function label(el){if(!el)return '';return n((el.textContent||'')+' '+(el.getAttribute('aria-label')||'')+' '+(el.getAttribute('title')||''));}" +
                "function tagText(el){if(!el)return null;var x=el.querySelector('[data-animeav1-download-text]');if(x)return x;var w=document.createTreeWalker(el,NodeFilter.SHOW_TEXT),t;while((t=w.nextNode())){if(n(t.nodeValue).indexOf('descarg')===0){var s=document.createElement('span');s.setAttribute('data-animeav1-download-text','1');s.textContent=t.nodeValue;t.parentNode.replaceChild(s,t);return s;}}return null;}" +
                "function replaceCatalog(el){if(!el)return;var w=document.createTreeWalker(el,NodeFilter.SHOW_TEXT),t;while((t=w.nextNode())){var z=n(t.nodeValue);if(z==='catálogo'||z==='catalogo'){t.nodeValue=t.nodeValue.replace(/catálogo|catalogo/i,'Descargas');break;}}}" +
                "function patchNav(){var cat=document.querySelector('[data-animeav1-downloads-link]');if(!cat){cat=[].slice.call(document.querySelectorAll('a[href],button')).find(function(e){var z=n(e.textContent);return z==='catálogo'||z==='catalogo'||z==='descargas';});}if(!cat)return;cat.setAttribute('data-animeav1-downloads-link','1');replaceCatalog(cat);var box=cat.closest('[data-animeav1-app-nav]');if(!box){var p=cat;for(var i=0;i<8&&p;i++,p=p.parentElement){var tx=n(p.innerText);if(tx.indexOf('inicio')>=0&&tx.indexOf('horario')>=0&&tx.indexOf('mis listas')>=0&&tx.indexOf('mi cuenta')>=0){box=p;break;}}}if(box&&box!==document.body&&box!==document.documentElement){box.setAttribute('data-animeav1-app-nav','1');box.style.setProperty('position','fixed','important');box.style.setProperty('left','0','important');box.style.setProperty('right','0','important');box.style.setProperty('bottom','0','important');box.style.setProperty('z-index','2147483300','important');box.style.setProperty('margin','0','important');box.style.setProperty('width','100%','important');box.style.setProperty('padding-bottom','env(safe-area-inset-bottom)','important');var h=Math.max(56,Math.ceil(box.getBoundingClientRect().height));document.body.style.setProperty('padding-bottom','calc('+h+'px + env(safe-area-inset-bottom))','important');}if(cat.tagName==='A')cat.setAttribute('href','animeav1://downloads');}" +
                "if(!window.__animeav1DownloadsNavCapture){window.__animeav1DownloadsNavCapture=true;document.addEventListener('click',function(e){var el=e.target&&e.target.closest?e.target.closest('[data-animeav1-downloads-link]'):null;if(!el)return;e.preventDefault();e.stopImmediatePropagation();location.href='animeav1://downloads';},true);}" +
                "function patchFooterVersion(){var existing=document.getElementById('animeav1-android-version');if(existing){existing.textContent=window.__animeav1AndroidVersion;return;}var candidates=[].slice.call(document.querySelectorAll('footer,div,p,span'));var fan=candidates.find(function(e){return n(e.textContent)==='by fans for fans';});if(!fan)return;var v=document.createElement('div');v.id='animeav1-android-version';v.textContent=window.__animeav1AndroidVersion;v.style.cssText='margin-top:6px;text-align:center;font-size:12px;line-height:1.4;color:#8f92ad;opacity:.9;font-family:inherit;';fan.insertAdjacentElement('afterend',v);}" +
                "function episodeDownloadElement(){if(!/^\\/media\\/[^/]+\\/\\d+\\/?$/.test(location.pathname))return null;return [].slice.call(document.querySelectorAll('a,button,[role=button]')).find(function(e){if(e.closest('[data-animeav1-app-nav]'))return false;return label(e).indexOf('descarg')===0;})||null;}" +
                "function sourceFor(el){if(!el)return '';var a=el.matches('a[href]')?el:el.closest('a[href]');if(!a)a=el.querySelector&&el.querySelector('a[href]');var raw=a?a.getAttribute('href'):(el.getAttribute('data-url')||el.getAttribute('data-href')||el.getAttribute('data-link')||'');try{if(raw&&raw!=='#'&&!/^javascript:/i.test(raw))return new URL(raw,location.href).href;}catch(e){}var oc=el.getAttribute('onclick')||'';var m=oc.match(/https?:\\/\\/(?:www\\.)?mega\\.(?:nz|co\\.nz)\\/[^'\"\\s)]+/i);return m?m[0]:'';}" +
                "function nativeDownload(el){var p=location.pathname.split('/');var slug=p.length>2?p[2]:'';var ep=p.length>3?p[3]:'';var h=document.querySelector('h1');var title=h?(h.textContent||'').trim():document.title;var src=sourceFor(el);location.href='animeav1://download?slug='+encodeURIComponent(slug)+'&episode='+encodeURIComponent(ep)+'&page='+encodeURIComponent(location.href)+'&title='+encodeURIComponent(title)+'&source='+encodeURIComponent(src);}" +
                "function patchDownload(){var b=episodeDownloadElement();if(!b)return;b.setAttribute('data-animeav1-native-download','1');var t=tagText(b);if(t)t.textContent=window.__animeav1AndroidLabel||'Descargar';}" +
                "if(!window.__animeav1AndroidDownloadCapture){window.__animeav1AndroidDownloadCapture=true;document.addEventListener('click',function(e){if(!/^\\/media\\/[^/]+\\/\\d+\\/?$/.test(location.pathname))return;var el=e.target&&e.target.closest?e.target.closest('a,button,[role=button]'):null;if(!el||el.closest('[data-animeav1-app-nav]'))return;if(label(el).indexOf('descarg')!==0)return;e.preventDefault();e.stopImmediatePropagation();nativeDownload(el);},true);}" +
                "function shareButton(){return [].slice.call(document.querySelectorAll('button,a,[role=button]')).find(function(e){var z=label(e);return z.indexOf('compartir')>=0||z.indexOf('share')>=0;})||null;}" +
                "function publishedEpisodeCount(slug){var max=0;[].slice.call(document.querySelectorAll('a[href]')).forEach(function(a){try{var u=new URL(a.getAttribute('href'),location.href),m=u.pathname.match(new RegExp('^/media/'+slug.replace(/[.*+?^${}()|[\\]\\\\]/g,'\\$&')+'/(\\\\d+)/?$'));if(m){var ep=parseInt(m[1],10)||0;if(ep>max)max=ep;}}catch(e){}});return max;}" +
                "function patchSeriesDownload(){var m=location.pathname.match(/^\\/media\\/([^/]+)\\/?$/);if(!m)return;var share=shareButton();if(!share)return;var b=document.getElementById('animeav1-download-unwatched');if(!b){b=document.createElement('button');b.id='animeav1-download-unwatched';b.type='button';b.className=share.className;b.setAttribute('aria-label','Descargar episodios no vistos');b.setAttribute('title','Descargar episodios no vistos');b.innerHTML='<span class=\"animeav1-series-arrow\"><svg viewBox=\"0 0 24 24\" width=\"22\" height=\"22\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><path d=\"M12 3v11\"/><path d=\"m7 10 5 5 5-5\"/><path d=\"M5 20h14\"/></svg></span><svg viewBox=\"0 0 24 24\" width=\"20\" height=\"20\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><path d=\"M3 3l18 18\"/><path d=\"M10.6 10.6a2 2 0 0 0 2.8 2.8\"/><path d=\"M9.9 4.2A10.5 10.5 0 0 1 21 12a15.7 15.7 0 0 1-2.1 3\"/><path d=\"M6.6 6.6A15.5 15.5 0 0 0 3 12a15.7 15.7 0 0 0 8.7 6.7\"/></svg>';b.style.display='inline-flex';b.style.alignItems='center';b.style.justifyContent='center';b.style.gap='2px';b.addEventListener('click',function(e){e.preventDefault();e.stopImmediatePropagation();var published=publishedEpisodeCount(m[1]);if(!published){alert('No se pudo determinar cuántos episodios están publicados');return;}b.classList.add('animeav1-series-downloading');location.href='animeav1://series-download?slug='+encodeURIComponent(m[1])+'&published='+published;setTimeout(function(){b.classList.remove('animeav1-series-downloading');},1200);},true);share.parentNode.insertBefore(b,share);}}" +
                "function ensureStyle(){if(document.getElementById('animeav1-native-style'))return;var s=document.createElement('style');s.id='animeav1-native-style';s.textContent='@keyframes animeav1DownloadBounce{0%,100%{transform:translateY(-3px);opacity:.45}55%{transform:translateY(3px);opacity:1}}.animeav1-series-downloading .animeav1-series-arrow{display:inline-flex;animation:animeav1DownloadBounce .9s ease-in-out infinite}';document.head.appendChild(s);}" +
                "function notifyLibraryChanged(){clearTimeout(window.__animeav1LibraryChangedTimer);window.__animeav1LibraryChangedTimer=setTimeout(function(){location.href='animeav1://library-changed';},350);}" +
                "function libraryAction(u,m){u=String(u||'');m=String(m||'GET').toUpperCase();return m!=='GET'&&(u.indexOf('?/library')>=0||u.indexOf('/cuenta/listas')>=0&&u.indexOf('library')>=0);}" +
                "if(!window.__animeav1FetchHook&&window.fetch){window.__animeav1FetchHook=true;var of=window.fetch;window.fetch=function(){var a=arguments,r=a[0],o=a[1]||{},u=typeof r==='string'?r:(r&&r.url)||'',m=o.method||(r&&r.method)||'GET';return of.apply(this,a).then(function(res){if(libraryAction(u,m))notifyLibraryChanged();return res;});};}" +
                "if(!window.__animeav1XhrHook&&window.XMLHttpRequest){window.__animeav1XhrHook=true;var oo=XMLHttpRequest.prototype.open,os=XMLHttpRequest.prototype.send;XMLHttpRequest.prototype.open=function(m,u){this.__av1m=m;this.__av1u=u;return oo.apply(this,arguments);};XMLHttpRequest.prototype.send=function(){if(libraryAction(this.__av1u,this.__av1m))this.addEventListener('load',notifyLibraryChanged,{once:true});return os.apply(this,arguments);};}" +
                "function refresh(){ensureStyle();patchNav();patchFooterVersion();patchDownload();patchSeriesDownload();}" +
                "window.__animeav1AndroidRefresh=refresh;refresh();if(!window.__animeav1AndroidObserver){window.__animeav1AndroidObserver=new MutationObserver(function(){requestAnimationFrame(refresh);});window.__animeav1AndroidObserver.observe(document.documentElement,{childList:true,subtree:true});}" +
                "})()";
    }

    static String updateDownloadLabel(String downloadLabel) {
        return "(function(){window.__animeav1AndroidLabel=" + JSONObject.quote(downloadLabel) + ";if(window.__animeav1AndroidRefresh)window.__animeav1AndroidRefresh();})()";
    }
}
