package com.ovelayos.animeav1;

import org.json.JSONObject;

final class SiteScripts {
    static String install(String localState,boolean tvMode){
        return "(function(){'use strict';window.__av1LocalState="+JSONObject.quote(localState)+";var tv="+tvMode+";"+
                "function norm(v){return String(v||'').trim().toLowerCase();}"+
                "function parts(){var p=location.pathname.split('/').filter(Boolean);return p[0]==='media'?p:[];}"+
                "function episode(){var p=parts();return p.length===3&&/^\\d+$/.test(p[2])?p:[];}"+
                "function source(el){var a=el&&(el.matches('a[href]')?el:el.closest('a[href]'));var r=a&&a.getAttribute('href')||el&&el.getAttribute('data-url')||'';try{return r&&r!=='#'?new URL(r,location.href).href:'';}catch(e){return '';}}"+
                "function footer(){var text="+JSONObject.quote("AnimeAV1 Android v"+BuildConfig.VERSION_NAME)+",old=document.getElementById('av1-android-version');if(old){old.textContent=text;return;}var w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT),n=null;while(w.nextNode()){if(norm(w.currentNode.nodeValue)==='by fans for fans'){n=w.currentNode;break;}}if(!n)return;var fan=n.parentElement;while(fan.parentElement&&fan.parentElement!==document.body&&norm(fan.parentElement.innerText)==='by fans for fans')fan=fan.parentElement;var v=document.createElement('div');v.id='av1-android-version';v.textContent=text;v.style.cssText='display:block;width:100%;text-align:center;margin:7px auto 0;color:#9b99aa;font-size:12px;line-height:1.4;font-family:inherit';fan.insertAdjacentElement('afterend',v);}"+
                "function hideWebNav(){var s=document.getElementById('av1-app-css');if(!s){s=document.createElement('style');s.id='av1-app-css';s.textContent='body{padding-bottom:0!important}@keyframes av1Bounce{0%,100%{transform:translateY(-3px)}50%{transform:translateY(4px)}}.av1-busy .av1-arrow{display:inline-flex;animation:av1Bounce .7s infinite}'+(tv?'a:focus,button:focus,[role=button]:focus,[tabindex]:focus{outline:3px solid #20d6c7!important;outline-offset:3px!important;border-radius:6px!important}':'');document.head.appendChild(s);}document.querySelectorAll('nav').forEach(function(n){var original=n.querySelector('.ic-home-smile')&&n.querySelector('.ic-layers-two-01')&&n.querySelector('.ic-calendar')&&n.querySelector('.ic-user-01'),t=norm(n.innerText),matches=['inicio','horario','mis listas','mi cuenta'].filter(function(x){return t.indexOf(x)>=0;}).length;if(original||matches===4){n.style.setProperty('display','none','important');n.setAttribute('aria-hidden','true');n.querySelectorAll('a,button,[tabindex]').forEach(function(x){x.tabIndex=-1;});}});}"+
                "function tvFocus(){if(!tv)return;document.querySelectorAll('[role=button],iframe[src*=\\\"challenges.cloudflare.com\\\"],iframe[title*=\\\"Cloudflare\\\" i]').forEach(function(x){if(!x.hasAttribute('tabindex'))x.tabIndex=0;});}"+
                "function tvKeys(){if(!tv||window.__av1TvKeys)return;window.__av1TvKeys=1;function visible(x){var r=x.getBoundingClientRect(),s=getComputedStyle(x);return r.width>0&&r.height>0&&s.visibility!=='hidden'&&s.display!=='none';}function controls(){return [].slice.call(document.querySelectorAll('a[href],button,input,select,textarea,iframe[src*=\\\"challenges.cloudflare.com\\\"],iframe[title*=\\\"Cloudflare\\\" i],[role=button],[tabindex]:not([tabindex=\\\"-1\\\"])')).filter(visible);}document.addEventListener('keydown',function(e){var active=document.activeElement,editable=/^(INPUT|TEXTAREA|SELECT)$/.test(active&&active.tagName);if(!/^Arrow/.test(e.key)||active&&active.tagName==='VIDEO'||active&&active.isContentEditable||editable&&(e.key==='ArrowLeft'||e.key==='ArrowRight'))return;var all=controls();if(!all.length)return;var current=active,target=null;if(!current||current===document.body||current===document.documentElement||!visible(current))target=all[0];else{var r=current.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,best=Infinity;all.forEach(function(x){if(x===current)return;var q=x.getBoundingClientRect(),dx=q.left+q.width/2-cx,dy=q.top+q.height/2-cy,primary=0,secondary=0,horizontal=e.key==='ArrowRight'||e.key==='ArrowLeft',aligned=horizontal?q.bottom>r.top+4&&q.top<r.bottom-4:q.right>r.left+4&&q.left<r.right-4;if(e.key==='ArrowRight'&&dx>8){primary=dx;secondary=Math.abs(dy);}else if(e.key==='ArrowLeft'&&dx< -8){primary=-dx;secondary=Math.abs(dy);}else if(e.key==='ArrowDown'&&dy>8){primary=dy;secondary=Math.abs(dx);}else if(e.key==='ArrowUp'&&dy< -8){primary=-dy;secondary=Math.abs(dx);}else return;var score=(aligned?0:100000)+primary*10+secondary;if(score<best){best=score;target=x;}});}if(target){e.preventDefault();target.focus();target.scrollIntoView({block:'center',inline:'nearest'});}else if(e.key==='ArrowRight'){e.preventDefault();AnimeAV1Android.focusNavigation();}},true);}"+
                "function patchWindows(){if(window.__av1Windows)return;window.__av1Windows=1;function safe(u,a){try{var x=new URL(u,location.href),image=/\\.(?:jpe?g|png|gif|webp|avif)(?:$|[?#])/i.test(x.href),discord=x.hostname==='discord.gg'||x.hostname==='discord.com'||x.hostname.endsWith('.discord.com')||x.hostname==='discordapp.com'||x.hostname.endsWith('.discordapp.com');return x.origin===location.origin||discord||image||!!(a&&a.querySelector&&a.querySelector('img'));}catch(_){return false;}}document.addEventListener('click',function(e){var a=e.target&&e.target.closest&&e.target.closest('a[target=\\\"_blank\\\"][href]');if(!a)return;e.preventDefault();e.stopImmediatePropagation();if(safe(a.href,a))location.href=a.href;},true);window.open=function(u){if(u&&safe(u,null))location.href=new URL(u,location.href).href;return null;};}"+
                "function download(){var p=episode();if(!p.length)return;var buttons=[].slice.call(document.querySelectorAll('a,button,[role=button]'));var b=buttons.find(function(x){return norm((x.textContent||'')+' '+(x.title||'')+' '+(x.getAttribute('aria-label')||'')).indexOf('descarg')>=0&&!x.id.startsWith('av1-');});if(!b)return;b.dataset.av1Native='1';if(!window.__av1DownloadCapture){window.__av1DownloadCapture=1;document.addEventListener('click',function(e){var x=e.target&&e.target.closest&&e.target.closest('[data-av1-native]');if(!x)return;e.preventDefault();e.stopImmediatePropagation();var q=episode();AnimeAV1Android.download(q[1],parseInt(q[2]),document.querySelector('h1')&&document.querySelector('h1').textContent||document.title,location.href,source(x));},true);}}"+
                "function seriesButton(){var p=parts();if(p.length!==2||document.getElementById('av1-unwatched'))return;var controls=[].slice.call(document.querySelectorAll('a,button,[role=button]'));var share=controls.find(function(x){var t=norm((x.textContent||'')+' '+(x.title||'')+' '+(x.getAttribute('aria-label')||''));return t.indexOf('compartir')>=0||t.indexOf('share')>=0;});if(!share)return;var b=document.createElement('button');b.id='av1-unwatched';b.type='button';b.className=share.className;b.title='Descargar no vistos';b.setAttribute('aria-label','Descargar no vistos');b.innerHTML='<span class=\\\"av1-arrow\\\"><svg viewBox=\\\"0 0 24 24\\\" width=\\\"21\\\" height=\\\"21\\\" fill=\\\"none\\\" stroke=\\\"currentColor\\\" stroke-width=\\\"2\\\"><path d=\\\"M12 3v12m-5-5 5 5 5-5M5 21h14\\\"/></svg></span><svg viewBox=\\\"0 0 24 24\\\" width=\\\"20\\\" height=\\\"20\\\" fill=\\\"none\\\" stroke=\\\"currentColor\\\" stroke-width=\\\"2\\\"><path d=\\\"M3 3l18 18M10.6 10.6a2 2 0 0 0 2.8 2.8M9.9 4.2A10.5 10.5 0 0 1 21 12a15 15 0 0 1-2.1 3M6.6 6.6A15 15 0 0 0 3 12a15.7 15.7 0 0 0 8.7 6.7\\\"/></svg>';b.onclick=function(e){e.preventDefault();e.stopPropagation();var max=0;document.querySelectorAll('a[href]').forEach(function(a){try{var x=new URL(a.href).pathname.split('/').filter(Boolean);if(x[0]==='media'&&x[1]===p[1]&&/^\\d+$/.test(x[2]))max=Math.max(max,parseInt(x[2]));}catch(_){} });b.classList.add('av1-busy');AnimeAV1Android.downloadUnwatched(p[1],document.querySelector('h1')&&document.querySelector('h1').textContent||p[1],max);setTimeout(function(){b.classList.remove('av1-busy');},1000);};share.parentNode.insertBefore(b,share);}"+
                "function offline(){var p=episode(),old=document.getElementById('av1-play-local');if(!p.length||window.__av1LocalState!=='completed'){if(old)old.remove();return;}if(old)return;var b=document.createElement('button');b.id='av1-play-local';b.textContent='▶ Ver copia offline';b.style.cssText='position:fixed;right:16px;bottom:18px;z-index:2147483640;background:#20d6c7;color:#101016;border:0;border-radius:18px;padding:12px 16px;font-weight:700';b.onclick=function(){AnimeAV1Android.playLocal(p[1],parseInt(p[2]));};document.body.appendChild(b);}"+
                "function refresh(){hideWebNav();footer();patchWindows();download();seriesButton();offline();tvFocus();tvKeys();}"+
                "refresh();if(!window.__av1Observer){window.__av1Observer=new MutationObserver(function(){requestAnimationFrame(refresh);});window.__av1Observer.observe(document.documentElement,{childList:true,subtree:true});}})();";
    }
    static String openWatchingList(){
        return "(function(){var tries=0;function norm(v){return String(v||'').replace(/\\s+/g,' ').trim().toLowerCase();}function open(){var controls=[].slice.call(document.querySelectorAll('button,a,[role=tab],[role=button]'));var watching=controls.find(function(x){return norm(x.textContent)==='viendo'&&x.getClientRects().length;});if(watching){watching.click();return;}var options=[].slice.call(document.querySelectorAll('select option'));var option=options.find(function(x){return norm(x.textContent)==='viendo';});if(option&&option.parentElement){option.parentElement.value=option.value;option.parentElement.dispatchEvent(new Event('change',{bubbles:true}));return;}if(tries++<24)setTimeout(open,150);}open();})()";
    }
    static String openAccount(){
        return "(function(){var visible=function(x){return !!(x&&x.getClientRects().length);},buttons=[].slice.call(document.querySelectorAll('button,[role=button]')),login=document.querySelector('button[aria-label=\\\"Iniciar sesión\\\"]'),account=buttons.find(function(x){var label=String(x.getAttribute('aria-label')||x.textContent||'').trim().toLowerCase();return visible(x)&&(label==='mi cuenta'||label.indexOf('cuenta')>=0);});var target=visible(login)?login:account;if(!target)return false;target.click();setTimeout(function(){var first=document.querySelector('input:not([type=hidden]),button[type=submit],iframe[src*=\\\"challenges.cloudflare.com\\\"],iframe[title*=\\\"Cloudflare\\\" i]');if(first){first.tabIndex=0;first.focus();}},180);return true;})()";
    }
    private SiteScripts(){}
}
