package com.ovelayos.animeav1;

import org.json.JSONObject;

final class SiteScripts {
    static String install(String localState){
        return "(function(){'use strict';window.__av1LocalState="+JSONObject.quote(localState)+";"+
                "function norm(v){return String(v||'').trim().toLowerCase();}"+
                "function parts(){var p=location.pathname.split('/').filter(Boolean);return p[0]==='media'?p:[];}"+
                "function episode(){var p=parts();return p.length===3&&/^\\d+$/.test(p[2])?p:[];}"+
                "function source(el){var a=el&&(el.matches('a[href]')?el:el.closest('a[href]'));var r=a&&a.getAttribute('href')||el&&el.getAttribute('data-url')||'';try{return r&&r!=='#'?new URL(r,location.href).href:'';}catch(e){return '';}}"+
                "function footer(){if(document.getElementById('av1-android-version'))return;var all=[].slice.call(document.querySelectorAll('footer *'));var fan=all.find(function(x){return norm(x.textContent)==='by fans for fans';});if(fan){var v=document.createElement('div');v.id='av1-android-version';v.textContent="+JSONObject.quote("AnimeAV1 Android v"+BuildConfig.VERSION_NAME)+";v.style.cssText='text-align:center;margin-top:6px;color:#9b99aa;font-size:12px';fan.insertAdjacentElement('afterend',v);}}"+
                "function hideWebNav(){var s=document.getElementById('av1-app-css');if(!s){s=document.createElement('style');s.id='av1-app-css';s.textContent='body{padding-bottom:0!important} nav[data-bottom-navigation],.fixed.bottom-0:has(a[href=\\\"/horario\\\"]){display:none!important}@keyframes av1Bounce{0%,100%{transform:translateY(-3px)}50%{transform:translateY(4px)}}.av1-busy .av1-arrow{animation:av1Bounce .7s infinite}';document.head.appendChild(s);}}"+
                "function patchWindows(){if(window.__av1Windows)return;window.__av1Windows=1;document.addEventListener('click',function(e){var a=e.target&&e.target.closest&&e.target.closest('a[target=\\\"_blank\\\"][href]');if(!a)return;e.preventDefault();location.href=a.href;},true);window.open=function(u){if(u)location.href=new URL(u,location.href).href;return window;};}"+
                "function download(){var p=episode();if(!p.length)return;var buttons=[].slice.call(document.querySelectorAll('a,button,[role=button]'));var b=buttons.find(function(x){return norm((x.textContent||'')+' '+(x.title||'')+' '+(x.getAttribute('aria-label')||'')).indexOf('descarg')>=0&&!x.id.startsWith('av1-');});if(!b)return;b.dataset.av1Native='1';if(!window.__av1DownloadCapture){window.__av1DownloadCapture=1;document.addEventListener('click',function(e){var x=e.target&&e.target.closest&&e.target.closest('[data-av1-native]');if(!x)return;e.preventDefault();e.stopImmediatePropagation();var q=episode();AnimeAV1Android.download(q[1],parseInt(q[2]),document.querySelector('h1')&&document.querySelector('h1').textContent||document.title,location.href,source(x));},true);}}"+
                "function seriesButton(){var p=parts();if(p.length!==2||document.getElementById('av1-unwatched'))return;var controls=[].slice.call(document.querySelectorAll('a,button,[role=button]'));var share=controls.find(function(x){var t=norm((x.textContent||'')+' '+(x.title||'')+' '+(x.getAttribute('aria-label')||''));return t.indexOf('compartir')>=0||t.indexOf('share')>=0;});if(!share)return;var b=document.createElement('button');b.id='av1-unwatched';b.type='button';b.className=share.className;b.title='Descargar no vistos';b.setAttribute('aria-label','Descargar no vistos');b.innerHTML='<span class=\\\"av1-arrow\\\">⇩</span>&nbsp;◉̸';b.onclick=function(e){e.preventDefault();e.stopPropagation();var max=0;document.querySelectorAll('a[href]').forEach(function(a){try{var x=new URL(a.href).pathname.split('/').filter(Boolean);if(x[0]==='media'&&x[1]===p[1]&&/^\\d+$/.test(x[2]))max=Math.max(max,parseInt(x[2]));}catch(_){} });b.classList.add('av1-busy');AnimeAV1Android.downloadUnwatched(p[1],document.querySelector('h1')&&document.querySelector('h1').textContent||p[1],max);setTimeout(function(){b.classList.remove('av1-busy');},1000);};share.parentNode.insertBefore(b,share);}"+
                "function offline(){var p=episode(),old=document.getElementById('av1-play-local');if(!p.length||window.__av1LocalState!=='completed'){if(old)old.remove();return;}if(old)return;var b=document.createElement('button');b.id='av1-play-local';b.textContent='▶ Ver copia offline';b.style.cssText='position:fixed;right:16px;bottom:18px;z-index:2147483640;background:#20d6c7;color:#101016;border:0;border-radius:18px;padding:12px 16px;font-weight:700';b.onclick=function(){AnimeAV1Android.playLocal(p[1],parseInt(p[2]));};document.body.appendChild(b);}"+
                "function swipe(){if(window.__av1Swipe)return;window.__av1Swipe=1;var sx=0,sy=0;document.addEventListener('touchstart',function(e){sx=0;if(e.touches.length!==1)return;var t=e.target;if(t&&t.closest&&t.closest('video,iframe,input,textarea,select,[contenteditable],button,a,[class*=swiper],[class*=carousel],[class*=slider],[role=slider]'))return;for(var n=t;n&&n!==document.body;n=n.parentElement){if(n.scrollWidth>n.clientWidth+8&&/(auto|scroll)/.test(getComputedStyle(n).overflowX))return;}sx=e.touches[0].clientX;sy=e.touches[0].clientY;},{passive:true});document.addEventListener('touchend',function(e){if(!sx||e.changedTouches.length!==1)return;var dx=e.changedTouches[0].clientX-sx,dy=e.changedTouches[0].clientY-sy;sx=0;if(Math.abs(dx)>100&&Math.abs(dx)>Math.abs(dy)*1.7&&Math.abs(dy)<75)AnimeAV1Android.swipe(dx<0?1:-1);},{passive:true});}"+
                "function refresh(){hideWebNav();footer();patchWindows();download();seriesButton();offline();swipe();}"+
                "refresh();if(!window.__av1Observer){window.__av1Observer=new MutationObserver(function(){requestAnimationFrame(refresh);});window.__av1Observer.observe(document.documentElement,{childList:true,subtree:true});}})();";
    }
    private SiteScripts(){}
}
