package com.ovelayos.animeav1;

import org.json.JSONObject;

final class SiteIntegration {
    private SiteIntegration() {}

    static String install(String downloadLabel) {
        return "(function(){window.__animeav1AndroidLabel=" + JSONObject.quote(downloadLabel) +
                ";window.__animeav1AndroidVersion=" + JSONObject.quote("AnimeAV1 Android v" + BuildConfig.VERSION_NAME) + ";" + """
                function n(s){return String(s||'').trim().toLowerCase().replace(/ +/g,' ');}
                function label(el){if(!el)return '';return n((el.textContent||'')+' '+(el.getAttribute('aria-label')||'')+' '+(el.getAttribute('title')||''));}
                function tagText(el){if(!el)return null;var x=el.querySelector('[data-animeav1-download-text]');if(x)return x;var w=document.createTreeWalker(el,NodeFilter.SHOW_TEXT),t;while((t=w.nextNode())){if(n(t.nodeValue).indexOf('descarg')===0){var s=document.createElement('span');s.setAttribute('data-animeav1-download-text','1');s.textContent=t.nodeValue;t.parentNode.replaceChild(s,t);return s;}}return null;}
                function hideSiteNav(){document.querySelectorAll('nav a[href=\"/catalogo\"]').forEach(function(a){var nav=a.closest('nav');if(nav)nav.style.setProperty('display','none','important');});}
                function patchFooterVersion(){var footer=document.querySelector('footer');if(!footer)return;var v=document.getElementById('animeav1-android-version');if(!v){var fan=[].slice.call(footer.querySelectorAll('span')).find(function(e){return n(e.textContent)==='by fans for fans'});if(!fan)return;v=document.createElement('div');v.id='animeav1-android-version';v.style.cssText='font-size:12px;color:#8f92ad;padding-top:4px';fan.parentElement.appendChild(v);}if(v.textContent!==window.__animeav1AndroidVersion)v.textContent=window.__animeav1AndroidVersion;}
                function patchNewWindows(){if(window.__animeav1WindowOpenPatched)return;window.__animeav1WindowOpenPatched=true;document.addEventListener('click',function(e){var a=e.target&&e.target.closest?e.target.closest('a[target="_blank"][href]'):null;if(!a)return;var u=new URL(a.href,location.href);if(u.protocol!=='http:'&&u.protocol!=='https:')return;e.preventDefault();e.stopImmediatePropagation();location.assign(u.href);},true);window.open=function(url){if(url){var u=new URL(String(url),location.href);if(u.protocol==='http:'||u.protocol==='https:')location.assign(u.href);}return window;};}
                function episodeParts(){var p=location.pathname.split('/').filter(Boolean);return p.length===3&&p[0]==='media'&&/^[0-9]+$/.test(p[2])?p:null;}
                function episodeDownloadElement(){if(!episodeParts())return null;return document.querySelector('[data-animeav1-native-download]')||[].slice.call(document.querySelectorAll('a,button,[role=button]')).find(function(e){return label(e).indexOf('descarg')===0;})||null;}
                function sourceFor(el){if(!el)return '';var a=el.matches('a[href]')?el:el.closest('a[href]');if(!a)a=el.querySelector&&el.querySelector('a[href]');var raw=a?a.getAttribute('href'):(el.getAttribute('data-url')||el.getAttribute('data-href')||el.getAttribute('data-link')||'');try{if(raw&&raw!=='#'&&String(raw).indexOf('javascript:')!==0)return new URL(raw,location.href).href;}catch(e){}return '';}
                function nativeDownload(el){var p=episodeParts()||[];var slug=p.length>1?p[1]:'';var ep=p.length>2?p[2]:'';var h=document.querySelector('h1');var title=h?(h.textContent||'').trim():document.title;var src=sourceFor(el);location.href='animeav1://download?slug='+encodeURIComponent(slug)+'&episode='+encodeURIComponent(ep)+'&page='+encodeURIComponent(location.href)+'&title='+encodeURIComponent(title)+'&source='+encodeURIComponent(src);}
                function patchDownload(){var b=episodeDownloadElement();if(!b)return;b.setAttribute('data-animeav1-native-download','1');var t=tagText(b);if(t&&t.textContent!==(window.__animeav1AndroidLabel||'Descargar'))t.textContent=window.__animeav1AndroidLabel||'Descargar';}
                if(!window.__animeav1AndroidDownloadCapture){window.__animeav1AndroidDownloadCapture=true;document.addEventListener('click',function(e){if(!episodeParts())return;var el=e.target&&e.target.closest?e.target.closest('a,button,[role=button]'):null;if(!el)return;if(!el.hasAttribute('data-animeav1-native-download')&&label(el).indexOf('descarg')!==0)return;e.preventDefault();e.stopImmediatePropagation();nativeDownload(el);},true);}
                function shareButton(){return [].slice.call(document.querySelectorAll('button,a,[role=button]')).find(function(e){var z=label(e);return z.indexOf('compartir')>=0||z.indexOf('share')>=0;})||null;}
                function publishedEpisodeCount(slug){var max=0;[].slice.call(document.querySelectorAll('a[href]')).forEach(function(a){try{var u=new URL(a.getAttribute('href'),location.href),p=u.pathname.split('/').filter(Boolean);if(p.length===3&&p[0]==='media'&&p[1]===slug&&/^[0-9]+$/.test(p[2])){var ep=parseInt(p[2],10)||0;if(ep>max)max=ep;}}catch(e){}});return max;}
                function patchSeriesDownload(){var p=location.pathname.split('/').filter(Boolean);if(p.length!==2||p[0]!=='media')return;var slug=p[1];var share=shareButton();if(!share)return;var b=document.getElementById('animeav1-download-unwatched');if(!b){b=document.createElement('button');b.id='animeav1-download-unwatched';b.type='button';b.className=share.className;b.setAttribute('aria-label','Descargar episodios no vistos');b.setAttribute('title','Descargar episodios no vistos');b.innerHTML='<span class="animeav1-series-arrow"><svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 3v11"/><path d="m7 10 5 5 5-5"/><path d="M5 20h14"/></svg></span><svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 3l18 18"/><path d="M10.6 10.6a2 2 0 0 0 2.8 2.8"/><path d="M9.9 4.2A10.5 10.5 0 0 1 21 12a15.7 15.7 0 0 1-2.1 3"/><path d="M6.6 6.6A15.5 15.5 0 0 0 3 12a15.7 15.7 0 0 0 8.7 6.7"/></svg>';b.style.display='inline-flex';b.style.alignItems='center';b.style.justifyContent='center';b.style.gap='2px';b.addEventListener('click',function(e){e.preventDefault();e.stopImmediatePropagation();var published=publishedEpisodeCount(slug);if(!published){alert('No se pudo determinar cuántos episodios están publicados');return;}b.classList.add('animeav1-series-downloading');location.href='animeav1://series-download?slug='+encodeURIComponent(slug)+'&published='+published;setTimeout(function(){b.classList.remove('animeav1-series-downloading');},1200);},true);share.parentNode.insertBefore(b,share);}}
                function ensureStyle(){if(document.getElementById('animeav1-native-style'))return;var s=document.createElement('style');s.id='animeav1-native-style';s.textContent='@keyframes animeav1DownloadBounce{0%,100%{transform:translateY(-3px);opacity:.45}55%{transform:translateY(3px);opacity:1}}.animeav1-series-downloading .animeav1-series-arrow{display:inline-flex;animation:animeav1DownloadBounce .9s ease-in-out infinite}';document.head.appendChild(s);}
                if(!window.__animeav1SwipeNav){window.__animeav1SwipeNav=true;var sx=0,sy=0;document.addEventListener('touchstart',function(e){sx=0;if(e.touches.length!==1)return;var t=e.target;if(t&&t.closest&&t.closest('video,iframe,input,textarea,select,button,a,[role="button"],[contenteditable],[draggable="true"],[class*="swiper"],[class*="carousel"],[class*="slider"],[class*="gallery"],[data-carousel],[data-swipe],[role="slider"]'))return;for(var p=t;p&&p!==document.body;p=p.parentElement){if(p.scrollWidth>p.clientWidth+8&&/auto|scroll/.test(getComputedStyle(p).overflowX))return;}sx=e.touches[0].clientX;sy=e.touches[0].clientY;},{passive:true});document.addEventListener('touchcancel',function(){sx=0;},{passive:true});document.addEventListener('touchend',function(e){if(!sx||e.changedTouches.length!==1)return;var dx=e.changedTouches[0].clientX-sx,dy=e.changedTouches[0].clientY-sy;sx=0;if(Math.abs(dx)<110||Math.abs(dx)<Math.abs(dy)*1.7||Math.abs(dy)>70)return;try{window.AnimeAV1Android.swipe(dx<0?1:-1);}catch(x){}},{passive:true});}
                function notifyLibraryChanged(){clearTimeout(window.__animeav1LibraryChangedTimer);window.__animeav1LibraryChangedTimer=setTimeout(function(){location.href='animeav1://library-changed';},350);}
                function libraryAction(u,m){u=String(u||'');m=String(m||'GET').toUpperCase();return m!=='GET'&&(u.indexOf('?/library')>=0||u.indexOf('/cuenta/listas')>=0&&u.indexOf('library')>=0);}
                if(!window.__animeav1FetchHook&&window.fetch){window.__animeav1FetchHook=true;var of=window.fetch;window.fetch=function(){var a=arguments,r=a[0],o=a[1]||{},u=typeof r==='string'?r:(r&&r.url)||'',m=o.method||(r&&r.method)||'GET';return of.apply(this,a).then(function(res){if(libraryAction(u,m))notifyLibraryChanged();return res;});};}
                if(!window.__animeav1XhrHook&&window.XMLHttpRequest){window.__animeav1XhrHook=true;var oo=XMLHttpRequest.prototype.open,os=XMLHttpRequest.prototype.send;XMLHttpRequest.prototype.open=function(m,u){this.__av1m=m;this.__av1u=u;return oo.apply(this,arguments);};XMLHttpRequest.prototype.send=function(){if(libraryAction(this.__av1u,this.__av1m))this.addEventListener('load',notifyLibraryChanged,{once:true});return os.apply(this,arguments);};}
                function refresh(){ensureStyle();hideSiteNav();patchFooterVersion();patchNewWindows();patchDownload();patchSeriesDownload();}
                window.__animeav1AndroidRefresh=refresh;refresh();if(!window.__animeav1AndroidObserver){var queued=false;window.__animeav1AndroidObserver=new MutationObserver(function(){if(queued)return;queued=true;requestAnimationFrame(function(){queued=false;refresh();});});window.__animeav1AndroidObserver.observe(document.documentElement,{childList:true,subtree:true});}
                })()
                """;
    }

    static String updateDownloadLabel(String downloadLabel) {
        return "(function(){window.__animeav1AndroidLabel=" + JSONObject.quote(downloadLabel) + ";if(window.__animeav1AndroidRefresh)window.__animeav1AndroidRefresh();})()";
    }
}
