package com.ovelayos.animeav1;

import org.json.JSONObject;

final class SiteIntegration {
    private SiteIntegration() {}

    static String install(String downloadLabel) {
        return "(function(){window.__animeav1AndroidLabel=" + JSONObject.quote(downloadLabel) +
                ";window.__animeav1AndroidVersion=" + JSONObject.quote("AnimeAV1 Android v" + BuildConfig.VERSION_NAME) + ";" + """
                function n(s){return String(s||'').trim().toLowerCase().replace(/ +/g,' ');}
                function label(el){if(!el)return '';return n((el.textContent||'')+' '+(el.getAttribute('aria-label')||'')+' '+(el.getAttribute('title')||''));}
                function visible(el){if(!el||!el.isConnected)return false;var r=el.getBoundingClientRect(),s=getComputedStyle(el);return r.width>0&&r.height>0&&s.display!=='none'&&s.visibility!=='hidden'&&s.opacity!=='0';}
                function canon(el){var z=label(el);if(z==='catálogo'||z==='catalogo'||z==='descargas')return 'descargas';if(z==='inicio')return 'inicio';if(z==='horario')return 'horario';if(z==='mis listas'||z==='mis listas de anime')return 'mis listas';if(z==='mi cuenta'||z==='cuenta')return 'mi cuenta';return '';}
                function tagText(el){if(!el)return null;var x=el.querySelector('[data-animeav1-download-text]');if(x)return x;var w=document.createTreeWalker(el,NodeFilter.SHOW_TEXT),t;while((t=w.nextNode())){if(n(t.nodeValue).indexOf('descarg')===0){var s=document.createElement('span');s.setAttribute('data-animeav1-download-text','1');s.textContent=t.nodeValue;t.parentNode.replaceChild(s,t);return s;}}return null;}
                function replaceCatalog(el){if(!el)return;var w=document.createTreeWalker(el,NodeFilter.SHOW_TEXT),t;while((t=w.nextNode())){var z=n(t.nodeValue);if(z==='catálogo'||z==='catalogo'){t.nodeValue=t.nodeValue.replace(/catálogo|catalogo/i,'Descargas');break;}}}
                function navBox(){var boxes=[].slice.call(document.querySelectorAll('nav,footer,div')).filter(function(e){if(!visible(e))return false;var tx=n(e.innerText);if(tx.indexOf('inicio')<0||tx.indexOf('horario')<0||tx.indexOf('mis listas')<0||tx.indexOf('mi cuenta')<0)return false;var r=e.getBoundingClientRect();return r.bottom>innerHeight-220&&r.top<innerHeight;});boxes.sort(function(a,b){var ar=a.getBoundingClientRect(),br=b.getBoundingClientRect();var as=Math.abs(innerHeight-ar.bottom)+(ar.height>180?500:0),bs=Math.abs(innerHeight-br.bottom)+(br.height>180?500:0);return as-bs;});return boxes[0]||null;}
                function navItems(box){if(!box)return [];var seen={};return [].slice.call(box.querySelectorAll('a[href],button,[role=button]')).filter(visible).filter(function(e){var c=canon(e);if(!c||seen[c])return false;seen[c]=1;return true;});}
                function openDownloads(){try{if(window.AnimeAV1Android&&typeof window.AnimeAV1Android.openDownloads==='function'){window.AnimeAV1Android.openDownloads();return;}}catch(e){}location.href='animeav1://downloads';}
                function patchNav(){document.querySelectorAll('[data-animeav1-app-nav]').forEach(function(e){e.removeAttribute('data-animeav1-app-nav')});document.querySelectorAll('[data-animeav1-downloads-link]').forEach(function(e){e.removeAttribute('data-animeav1-downloads-link')});var box=navBox();if(!box)return;box.setAttribute('data-animeav1-app-nav','1');var items=navItems(box),cat=items.find(function(e){return canon(e)==='descargas'});if(!cat)return;cat.setAttribute('data-animeav1-downloads-link','1');replaceCatalog(cat);box.style.setProperty('position','fixed','important');box.style.setProperty('left','0','important');box.style.setProperty('right','0','important');box.style.setProperty('bottom','0','important');box.style.setProperty('z-index','2147483300','important');box.style.setProperty('margin','0','important');box.style.setProperty('width','100%','important');box.style.setProperty('padding-bottom','env(safe-area-inset-bottom)','important');var h=Math.max(56,Math.ceil(box.getBoundingClientRect().height));document.body.style.setProperty('padding-bottom','calc('+h+'px + env(safe-area-inset-bottom))','important');if(cat.tagName==='A')cat.setAttribute('href','animeav1://downloads');if(!cat.dataset.animeav1Bound){cat.dataset.animeav1Bound='1';cat.addEventListener('click',function(e){e.preventDefault();e.stopImmediatePropagation();openDownloads();},true);}}
                if(!window.__animeav1DownloadsNavCapture){window.__animeav1DownloadsNavCapture=true;document.addEventListener('click',function(e){var el=e.target&&e.target.closest?e.target.closest('a,button,[role=button]'):null,box=navBox();if(!el||!box||!box.contains(el)||canon(el)!=='descargas')return;e.preventDefault();e.stopImmediatePropagation();openDownloads();},true);}
                function patchFooterVersion(){var existing=document.getElementById('animeav1-android-version');if(existing){existing.textContent=window.__animeav1AndroidVersion;return;}var candidates=[].slice.call(document.querySelectorAll('footer,div,p,span'));var fan=candidates.find(function(e){return n(e.textContent)==='by fans for fans';});if(!fan)return;var v=document.createElement('div');v.id='animeav1-android-version';v.textContent=window.__animeav1AndroidVersion;v.style.cssText='margin-top:6px;text-align:center;font-size:12px;line-height:1.4;color:#8f92ad;opacity:.9;font-family:inherit;';fan.insertAdjacentElement('afterend',v);}
                function patchNewWindows(){document.querySelectorAll('a[target="_blank"]').forEach(function(a){a.setAttribute('target','_self')});if(!window.__animeav1WindowOpenPatched){window.__animeav1WindowOpenPatched=true;window.__animeav1OriginalOpen=window.open;window.open=function(url){if(url){try{location.href=new URL(String(url),location.href).href;}catch(e){location.href=String(url);}}return window;};}}
                function episodeParts(){var p=location.pathname.split('/').filter(Boolean);return p.length===3&&p[0]==='media'&&/^[0-9]+$/.test(p[2])?p:null;}
                function episodeDownloadElement(){if(!episodeParts())return null;return [].slice.call(document.querySelectorAll('a,button,[role=button]')).find(function(e){if(e.closest('[data-animeav1-app-nav]'))return false;return label(e).indexOf('descarg')===0;})||null;}
                function sourceFor(el){if(!el)return '';var a=el.matches('a[href]')?el:el.closest('a[href]');if(!a)a=el.querySelector&&el.querySelector('a[href]');var raw=a?a.getAttribute('href'):(el.getAttribute('data-url')||el.getAttribute('data-href')||el.getAttribute('data-link')||'');try{if(raw&&raw!=='#'&&String(raw).indexOf('javascript:')!==0)return new URL(raw,location.href).href;}catch(e){}return '';}
                function nativeDownload(el){var p=episodeParts()||[];var slug=p.length>1?p[1]:'';var ep=p.length>2?p[2]:'';var h=document.querySelector('h1');var title=h?(h.textContent||'').trim():document.title;var src=sourceFor(el);location.href='animeav1://download?slug='+encodeURIComponent(slug)+'&episode='+encodeURIComponent(ep)+'&page='+encodeURIComponent(location.href)+'&title='+encodeURIComponent(title)+'&source='+encodeURIComponent(src);}
                function patchDownload(){var b=episodeDownloadElement();if(!b)return;b.setAttribute('data-animeav1-native-download','1');var t=tagText(b);if(t)t.textContent=window.__animeav1AndroidLabel||'Descargar';}
                if(!window.__animeav1AndroidDownloadCapture){window.__animeav1AndroidDownloadCapture=true;document.addEventListener('click',function(e){if(!episodeParts())return;var el=e.target&&e.target.closest?e.target.closest('a,button,[role=button]'):null;if(!el||el.closest('[data-animeav1-app-nav]'))return;if(label(el).indexOf('descarg')!==0)return;e.preventDefault();e.stopImmediatePropagation();nativeDownload(el);},true);}
                function shareButton(){return [].slice.call(document.querySelectorAll('button,a,[role=button]')).find(function(e){var z=label(e);return z.indexOf('compartir')>=0||z.indexOf('share')>=0;})||null;}
                function publishedEpisodeCount(slug){var max=0;[].slice.call(document.querySelectorAll('a[href]')).forEach(function(a){try{var u=new URL(a.getAttribute('href'),location.href),p=u.pathname.split('/').filter(Boolean);if(p.length===3&&p[0]==='media'&&p[1]===slug&&/^[0-9]+$/.test(p[2])){var ep=parseInt(p[2],10)||0;if(ep>max)max=ep;}}catch(e){}});return max;}
                function patchSeriesDownload(){var p=location.pathname.split('/').filter(Boolean);if(p.length!==2||p[0]!=='media')return;var slug=p[1];var share=shareButton();if(!share)return;var b=document.getElementById('animeav1-download-unwatched');if(!b){b=document.createElement('button');b.id='animeav1-download-unwatched';b.type='button';b.className=share.className;b.setAttribute('aria-label','Descargar episodios no vistos');b.setAttribute('title','Descargar episodios no vistos');b.innerHTML='<span class="animeav1-series-arrow"><svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 3v11"/><path d="m7 10 5 5 5-5"/><path d="M5 20h14"/></svg></span><svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 3l18 18"/><path d="M10.6 10.6a2 2 0 0 0 2.8 2.8"/><path d="M9.9 4.2A10.5 10.5 0 0 1 21 12a15.7 15.7 0 0 1-2.1 3"/><path d="M6.6 6.6A15.5 15.5 0 0 0 3 12a15.7 15.7 0 0 0 8.7 6.7"/></svg>';b.style.display='inline-flex';b.style.alignItems='center';b.style.justifyContent='center';b.style.gap='2px';b.addEventListener('click',function(e){e.preventDefault();e.stopImmediatePropagation();var published=publishedEpisodeCount(slug);if(!published){alert('No se pudo determinar cuántos episodios están publicados');return;}b.classList.add('animeav1-series-downloading');location.href='animeav1://series-download?slug='+encodeURIComponent(slug)+'&published='+published;setTimeout(function(){b.classList.remove('animeav1-series-downloading');},1200);},true);share.parentNode.insertBefore(b,share);}}
                function ensureStyle(){if(document.getElementById('animeav1-native-style'))return;var s=document.createElement('style');s.id='animeav1-native-style';s.textContent='@keyframes animeav1DownloadBounce{0%,100%{transform:translateY(-3px);opacity:.45}55%{transform:translateY(3px);opacity:1}}.animeav1-series-downloading .animeav1-series-arrow{display:inline-flex;animation:animeav1DownloadBounce .9s ease-in-out infinite}';document.head.appendChild(s);}
                function currentNavIndex(items){if(window.__animeav1DownloadsOpen){for(var i=0;i<items.length;i++)if(canon(items[i])==='descargas')return i;}for(var i=0;i<items.length;i++){var e=items[i],ar=n(e.getAttribute('aria-current')),cl=n(e.className||'');if(ar==='page'||cl.indexOf('active')>=0||cl.indexOf('selected')>=0)return i;}var path=location.pathname||'/';while(path.length>1&&path.endsWith('/'))path=path.slice(0,-1);for(var i=0;i<items.length;i++){var e=items[i],a=e.matches('a[href]')?e:e.closest('a[href]');if(a){try{var u=new URL(a.getAttribute('href'),location.href),p=u.pathname||'/';while(p.length>1&&p.endsWith('/'))p=p.slice(0,-1);if(u.host===location.host&&p===path)return i;}catch(x){}}}var want=path==='/'?'inicio':path.indexOf('/horario')===0?'horario':path.indexOf('/cuenta/listas')===0?'mis listas':path.indexOf('/cuenta')===0?'mi cuenta':'';for(var i=0;i<items.length;i++)if(canon(items[i])===want)return i;return -1;}
                function activateNavItem(el){if(!el)return;if(canon(el)==='descargas'){openDownloads();return;}var a=el.matches('a[href]')?el:el.closest('a[href]');if(a){var h=a.getAttribute('href');if(h&&h!=='#'){location.href=new URL(h,location.href).href;return;}}el.click();}
                if(!window.__animeav1SwipeNav){window.__animeav1SwipeNav=true;var sx=0,sy=0,st=null;document.addEventListener('touchstart',function(e){if(!e.touches||e.touches.length!==1)return;var t=e.target;if(t&&t.closest&&t.closest('video,iframe,input,textarea,select,[contenteditable],[class*="swiper"],[class*="carousel"],[data-carousel]'))return;var box=navBox(),items=navItems(box);if(currentNavIndex(items)<0)return;sx=e.touches[0].clientX;sy=e.touches[0].clientY;st=t;},{passive:true});document.addEventListener('touchend',function(e){if(!sx||!e.changedTouches||e.changedTouches.length!==1)return;var dx=e.changedTouches[0].clientX-sx,dy=e.changedTouches[0].clientY-sy;sx=0;sy=0;if(Math.abs(dx)<90||Math.abs(dx)<Math.abs(dy)*1.4||Math.abs(dy)>90)return;var box=navBox(),items=navItems(box),idx=currentNavIndex(items);if(idx<0)return;var next=dx<0?idx+1:idx-1;if(next<0||next>=items.length)return;activateNavItem(items[next]);},{passive:true});}
                function notifyLibraryChanged(){clearTimeout(window.__animeav1LibraryChangedTimer);window.__animeav1LibraryChangedTimer=setTimeout(function(){location.href='animeav1://library-changed';},350);}
                function libraryAction(u,m){u=String(u||'');m=String(m||'GET').toUpperCase();return m!=='GET'&&(u.indexOf('?/library')>=0||u.indexOf('/cuenta/listas')>=0&&u.indexOf('library')>=0);}
                if(!window.__animeav1FetchHook&&window.fetch){window.__animeav1FetchHook=true;var of=window.fetch;window.fetch=function(){var a=arguments,r=a[0],o=a[1]||{},u=typeof r==='string'?r:(r&&r.url)||'',m=o.method||(r&&r.method)||'GET';return of.apply(this,a).then(function(res){if(libraryAction(u,m))notifyLibraryChanged();return res;});};}
                if(!window.__animeav1XhrHook&&window.XMLHttpRequest){window.__animeav1XhrHook=true;var oo=XMLHttpRequest.prototype.open,os=XMLHttpRequest.prototype.send;XMLHttpRequest.prototype.open=function(m,u){this.__av1m=m;this.__av1u=u;return oo.apply(this,arguments);};XMLHttpRequest.prototype.send=function(){if(libraryAction(this.__av1u,this.__av1m))this.addEventListener('load',notifyLibraryChanged,{once:true});return os.apply(this,arguments);};}
                function refresh(){ensureStyle();patchNav();patchFooterVersion();patchNewWindows();patchDownload();patchSeriesDownload();}
                window.__animeav1AndroidRefresh=refresh;refresh();if(!window.__animeav1AndroidObserver){window.__animeav1AndroidObserver=new MutationObserver(function(){requestAnimationFrame(refresh);});window.__animeav1AndroidObserver.observe(document.documentElement,{childList:true,subtree:true});}
                })()
                """;
    }

    static String updateDownloadLabel(String downloadLabel) {
        return "(function(){window.__animeav1AndroidLabel=" + JSONObject.quote(downloadLabel) + ";if(window.__animeav1AndroidRefresh)window.__animeav1AndroidRefresh();})()";
    }
}
