package com.dart998.animeav1;

final class TvSiteScripts {
    static String install(){
        return "(function(){'use strict';"+
                "function visible(x){if(!x)return false;var r=x.getBoundingClientRect(),s=getComputedStyle(x);return r.width>0&&r.height>0&&s.visibility!=='hidden'&&s.display!=='none';}"+
                "function patchWindows(){if(window.__av1TvWindows)return;window.__av1TvWindows=1;function safe(u,a){try{var x=new URL(u,location.href),image=/\\.(?:jpe?g|png|gif|webp|avif)(?:$|[?#])/i.test(x.href),discord=x.hostname==='discord.gg'||x.hostname==='discord.com'||x.hostname.endsWith('.discord.com')||x.hostname==='discordapp.com'||x.hostname.endsWith('.discordapp.com');return x.origin===location.origin||discord||image||!!(a&&a.querySelector&&a.querySelector('img'));}catch(e){return false;}}document.addEventListener('click',function(e){var a=e.target&&e.target.closest&&e.target.closest('a[target=\"_blank\"][href]');if(!a)return;e.preventDefault();e.stopImmediatePropagation();if(safe(a.href,a))location.href=a.href;},true);window.open=function(u){if(u&&safe(u,null))location.href=new URL(u,location.href).href;return null;};}"+
                "function prepareFocus(){document.querySelectorAll('[role=button],iframe[src*=\"challenges.cloudflare.com\"],iframe[title*=\"Cloudflare\" i]').forEach(function(x){if(!x.hasAttribute('tabindex'))x.tabIndex=0;});}"+
                "function downloadIcon(){document.querySelectorAll('.ic-layers-two-01').forEach(function(x){if(x.dataset.av1Arrow)return;x.dataset.av1Arrow='1';var svg='<svg viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 3v13M7 11l5 5 5-5M5 21h14\"/></svg>';if(String(x.tagName).toLowerCase()==='svg'){x.setAttribute('viewBox','0 0 24 24');x.setAttribute('fill','none');x.setAttribute('stroke','currentColor');x.setAttribute('stroke-width','2');x.setAttribute('stroke-linecap','round');x.setAttribute('stroke-linejoin','round');x.innerHTML='<path d=\"M12 3v13M7 11l5 5 5-5M5 21h14\"/>';}else{x.innerHTML=svg;}});}"+
                "function controls(){return [].slice.call(document.querySelectorAll('a[href],button,input,select,textarea,iframe[src*=\"challenges.cloudflare.com\"],iframe[title*=\"Cloudflare\" i],[role=button],[tabindex]:not([tabindex=\"-1\"])')).filter(visible);}"+
                "function keys(){if(window.__av1TvKeys)return;window.__av1TvKeys=1;document.addEventListener('keydown',function(e){var active=document.activeElement,editable=/^(INPUT|TEXTAREA|SELECT)$/.test(active&&active.tagName);if(!/^Arrow/.test(e.key)||active&&active.tagName==='VIDEO'||active&&active.isContentEditable||editable&&(e.key==='ArrowLeft'||e.key==='ArrowRight'))return;var all=controls();if(!all.length)return;var target=null;if(!active||active===document.body||active===document.documentElement||!visible(active))target=all[0];else{var r=active.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,best=Infinity;all.forEach(function(x){if(x===active)return;var q=x.getBoundingClientRect(),dx=q.left+q.width/2-cx,dy=q.top+q.height/2-cy,primary=0,secondary=0,horizontal=e.key==='ArrowRight'||e.key==='ArrowLeft',aligned=horizontal?q.bottom>r.top+4&&q.top<r.bottom-4:q.right>r.left+4&&q.left<r.right-4;if(e.key==='ArrowRight'&&dx>8){primary=dx;secondary=Math.abs(dy);}else if(e.key==='ArrowLeft'&&dx< -8){primary=-dx;secondary=Math.abs(dy);}else if(e.key==='ArrowDown'&&dy>8){primary=dy;secondary=Math.abs(dx);}else if(e.key==='ArrowUp'&&dy< -8){primary=-dy;secondary=Math.abs(dx);}else return;var score=(aligned?0:100000)+primary*10+secondary;if(score<best){best=score;target=x;}});}if(target){e.preventDefault();target.focus();target.scrollIntoView({block:'center',inline:'nearest'});}},true);}"+
                "function refresh(){patchWindows();prepareFocus();downloadIcon();keys();}refresh();if(!window.__av1TvObserver){window.__av1TvObserver=new MutationObserver(function(){requestAnimationFrame(function(){prepareFocus();downloadIcon();});});window.__av1TvObserver.observe(document.documentElement,{childList:true,subtree:true});}})();";
    }

    private TvSiteScripts(){}
}
