package com.dart998.animeav1;

import org.json.JSONObject;

final class SiteScripts {
    static String install(String localState){
        return "(function(){'use strict';window.__av1LocalState="+JSONObject.quote(localState)+";"+
                "function norm(v){return String(v||'').trim().toLowerCase();}"+
                "function parts(){var p=location.pathname.split('/').filter(Boolean);return p[0]==='media'?p:[];}"+
                "function episode(){var p=parts();return p.length===3&&/^\\d+$/.test(p[2])?p:[];}"+
                "function source(el){var a=el&&(el.matches('a[href]')?el:el.closest('a[href]'));var r=a&&a.getAttribute('href')||el&&el.getAttribute('data-url')||'';try{return r&&r!=='#'?new URL(r,location.href).href:'';}catch(e){return '';}}"+
                "function footer(){var text="+JSONObject.quote("AnimeAV1 Android v"+BuildConfig.VERSION_NAME)+",old=document.getElementById('av1-android-version');if(old){old.textContent=text;return;}var w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT),n=null;while(w.nextNode()){if(norm(w.currentNode.nodeValue)==='by fans for fans'){n=w.currentNode;break;}}if(!n)return;var fan=n.parentElement;while(fan.parentElement&&fan.parentElement!==document.body&&norm(fan.parentElement.innerText)==='by fans for fans')fan=fan.parentElement;var v=document.createElement('div');v.id='av1-android-version';v.textContent=text;v.style.cssText='display:block;width:100%;text-align:center;margin:7px auto 0;color:#9b99aa;font-size:12px;line-height:1.4;font-family:inherit';fan.insertAdjacentElement('afterend',v);}"+
                "function hideWebNav(){var s=document.getElementById('av1-app-css');if(!s){s=document.createElement('style');s.id='av1-app-css';s.textContent='body{padding-bottom:0!important}@keyframes av1Bounce{0%,100%{transform:translateY(-3px)}50%{transform:translateY(4px)}}.av1-busy .av1-arrow{display:inline-flex;animation:av1Bounce .7s infinite}';document.head.appendChild(s);}document.querySelectorAll('nav').forEach(function(n){var t=' '+norm((n.innerText||n.textContent||'').replace(/\\s+/g,' '))+' ',bottom=n.querySelector('a[href=\\\"/horario\\\"]')&&t.indexOf(' inicio ')>=0&&(t.indexOf(' catálogo ')>=0||t.indexOf(' catalogo ')>=0)&&t.indexOf(' horario ')>=0&&t.indexOf(' mis listas ')>=0&&t.indexOf(' mi cuenta ')>=0;if(bottom)n.style.setProperty('display','none','important');});}"+
                "function patchWindows(){if(window.__av1Windows)return;window.__av1Windows=1;function safe(u,a){try{var x=new URL(u,location.href),image=/\\.(?:jpe?g|png|gif|webp|avif)(?:$|[?#])/i.test(x.href),discord=x.hostname==='discord.gg'||x.hostname==='discord.com'||x.hostname.endsWith('.discord.com')||x.hostname==='discordapp.com'||x.hostname.endsWith('.discordapp.com');return x.origin===location.origin||discord||image||!!(a&&a.querySelector&&a.querySelector('img'));}catch(_){return false;}}document.addEventListener('click',function(e){var a=e.target&&e.target.closest&&e.target.closest('a[target=\\\"_blank\\\"][href]');if(!a)return;e.preventDefault();e.stopImmediatePropagation();if(safe(a.href,a))location.href=a.href;},true);window.open=function(u){if(u&&safe(u,null))location.href=new URL(u,location.href).href;return null;};}"+
                "function download(){var p=episode();if(!p.length)return;var buttons=[].slice.call(document.querySelectorAll('a,button,[role=button]'));var b=buttons.find(function(x){return norm((x.textContent||'')+' '+(x.title||'')+' '+(x.getAttribute('aria-label')||'')).indexOf('descarg')>=0&&!x.id.startsWith('av1-');});if(!b)return;b.dataset.av1Native='1';if(!window.__av1DownloadCapture){window.__av1DownloadCapture=1;document.addEventListener('click',function(e){var x=e.target&&e.target.closest&&e.target.closest('[data-av1-native]');if(!x)return;e.preventDefault();e.stopImmediatePropagation();var q=episode();AnimeAV1Android.download(q[1],parseInt(q[2]),document.querySelector('h1')&&document.querySelector('h1').textContent||document.title,location.href,source(x));},true);}}"+
                "function seriesButton(){var p=parts();if(p.length!==2||document.getElementById('av1-unwatched'))return;var controls=[].slice.call(document.querySelectorAll('a,button,[role=button]'));var share=controls.find(function(x){var t=norm((x.textContent||'')+' '+(x.title||'')+' '+(x.getAttribute('aria-label')||''));return t.indexOf('compartir')>=0||t.indexOf('share')>=0;});if(!share)return;var b=document.createElement('button');b.id='av1-unwatched';b.type='button';b.className=share.className;b.title='Descargar no vistos';b.setAttribute('aria-label','Descargar no vistos');b.innerHTML='<span class=\\\"av1-arrow\\\"><svg viewBox=\\\"0 0 24 24\\\" width=\\\"21\\\" height=\\\"21\\\" fill=\\\"none\\\" stroke=\\\"currentColor\\\" stroke-width=\\\"2\\\"><path d=\\\"M12 3v12m-5-5 5 5 5-5M5 21h14\\\"/></svg></span><svg viewBox=\\\"0 0 24 24\\\" width=\\\"20\\\" height=\\\"20\\\" fill=\\\"none\\\" stroke=\\\"currentColor\\\" stroke-width=\\\"2\\\"><path d=\\\"M3 3l18 18M10.6 10.6a2 2 0 0 0 2.8 2.8M9.9 4.2A10.5 10.5 0 0 1 21 12a15 15 0 0 1-2.1 3M6.6 6.6A15 15 0 0 0 3 12a15.7 15.7 0 0 0 8.7 6.7\\\"/></svg>';b.onclick=function(e){e.preventDefault();e.stopPropagation();var max=0;document.querySelectorAll('a[href]').forEach(function(a){try{var x=new URL(a.href).pathname.split('/').filter(Boolean);if(x[0]==='media'&&x[1]===p[1]&&/^\\d+$/.test(x[2]))max=Math.max(max,parseInt(x[2]));}catch(_){} });b.classList.add('av1-busy');AnimeAV1Android.downloadUnwatched(p[1],document.querySelector('h1')&&document.querySelector('h1').textContent||p[1],max);setTimeout(function(){b.classList.remove('av1-busy');},1000);};share.parentNode.insertBefore(b,share);}"+
                "function offline(){var p=episode(),old=document.getElementById('av1-play-local');if(!p.length||window.__av1LocalState!=='completed'){if(old)old.remove();return;}if(old)return;var b=document.createElement('button');b.id='av1-play-local';b.textContent='▶ Ver copia offline';b.style.cssText='position:fixed;right:16px;bottom:18px;z-index:2147483640;background:#20d6c7;color:#101016;border:0;border-radius:18px;padding:12px 16px;font-weight:700';b.onclick=function(){AnimeAV1Android.playLocal(p[1],parseInt(p[2]));};document.body.appendChild(b);}"+
                "function refresh(){hideWebNav();footer();patchWindows();download();seriesButton();offline();}"+
                "refresh();if(!window.__av1Observer){window.__av1Observer=new MutationObserver(function(){requestAnimationFrame(refresh);});window.__av1Observer.observe(document.documentElement,{childList:true,subtree:true});}})();";
    }
    static String openWatchingList(){
        return "(function(){var tries=0;function norm(v){return String(v||'').replace(/\\s+/g,' ').trim().toLowerCase();}function open(){var controls=[].slice.call(document.querySelectorAll('button,a,[role=tab],[role=button]'));var watching=controls.find(function(x){return norm(x.textContent)==='viendo'&&x.getClientRects().length;});if(watching){watching.click();return;}var options=[].slice.call(document.querySelectorAll('select option'));var option=options.find(function(x){return norm(x.textContent)==='viendo';});if(option&&option.parentElement){option.parentElement.value=option.value;option.parentElement.dispatchEvent(new Event('change',{bubbles:true}));return;}if(tries++<24)setTimeout(open,150);}open();})()";
    }
    private SiteScripts(){}
}
